# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: lepecoder checkin

on:
  push:  # 推送时执行
    branches:
      - master
  schedule:  # 定时执行
    - cron: '0 0 * * *'
  watch:
    types: started

jobs:
  checkin:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
    - name: 'wps invite'
      run: python main.py _wps_invite
#     - name: 'youdao_checkin'
#       run: python note163.py ${{secrets.YOUDAO_USER}} ${{secrets.YOUDAO_PASSWD}}
      
